### ISSUE TITLE
add an --auto-confirm option

### ISSUE THREAD

**Issue by cryptomayor** [textury/arkb#1]
It is currently not possible to call the arkb cli for uploading in a script because the CLI will hang at the CONFIRM step

**Comment by cedriking** [comment]
Coming soon in v1.1.1 (https://github.com/textury/arkb/commit/4f6749466d29d7ed0982c3d5872f16328705c3c3) just waiting for a reply on https://github.com/textury/arkb/issues/2 to see if I can add this one too before the next release 👍🏼
