### ISSUE TITLE
show ipfs hash in 'deploy' command in case where arweave already deployed

### ISSUE THREAD

**Issue by cryptomayor** [textury/arkb#2]
Currently, if an upload happens, it will return the ipfs hash in the CLI command output.

In the case where no upload happens (idempotent), it will only return the arweave Id.

**Comment by cedriking** [comment]
Hey @cryptomayor , is this for single file deployment?

**Comment by cryptomayor** [comment]
Yep. Just a single file.

**Comment by cryptomayor** [comment]
Any updates on this?

**Comment by cedriking** [comment]
v1.1.1 has been released with this feature + the `--auto-confirm` option 👍🏼
