### ISSUE TITLE
Bundler funds not fetched correctly

### ISSUE THREAD

**Issue by kaldap** [textury/arkb#41]
Hello! I've been unable to upload data to the bundler because no funds on the bundler have been recognized.
After some digging, I've discovered that the cause is in the **Accept** HTTP header.
Arkb is sending `application/json, text/plain, */*`, but in this case, the server responds with zero balance.
When I sent the request manually with Accept set to `*/*` only, the server responded with the correct balance.
Not sure, if this is a problem with the arkb utility or with a configuration of that particular server.
Server used: `http://bundler.arweave.net:10000/`.

**Comment by cedriking** [comment]
Hey @kaldap , that bundler was marked as deprecated many weeks ago. I'm not sure how good of an idea is to keep using it. You can find the list of active bundlers here: https://bundlr.network/status

As you can see, right now only `https://node1.bundlr.network` and `https://node2.bundlr.network` are active nodes by the bundler creator, which was previously hosted on the URL you pointed out.

Most people are currently using `node1`.

**Comment by kaldap** [comment]
Thank you for the insight! I've re-tested the request with these nodes and it seems to be working as expected, so it is probably an server problem. For this reason, I am closing the issue.

**Comment by 0xMars4204** [comment]
> Thank you for the insight! I've re-tested the request with these nodes and it seems to be working as expected, so it is probably an server problem. For this reason, I am closing the issue.

Can you share the script you used?

```
arkb deploy --use-bundler https://node2.bundlr.network/ <path-to-metadata>
```

I tried above script, but no luck yet.

**Comment by kaldap** [comment]
Exactly what you wrote. I am running on Node 17, the latest version of arkb installed by npm.

If you'd like to verify your balance (to check whether it is arkb issue or not), visit `https://node1.bundlr.network/account/balance?address=<INSERT ADDRESS HERE>`.
According to the bundler node sources, it requires 25 confirmations and after that, it may take up to an hour to cache the transaction (it is a cron job with 1 hour period). So make sure that the bundler already received the balance.

Just to be sure, did you really send the amount there using `arkb fund-bundler <VALUE> --use-bundler https://node1.bundlr.network/`?

**Comment by 0xMars4204** [comment]
Thanks for the quick reply. Still waiting for confirmation on arweave.
I didn't know it requires too much confirmation.

Super thanks.
