### ISSUE TITLE
Bundlr Uploads don't work using arkb, but work fine using the bundlr client

### ISSUE THREAD

**Issue by garrettian** [textury/arkb#53]
Can you please advise users in the readme or in the program itself that they should use https://docs.bundlr.network/docs/client/cli for bundlr uploads? The arkb implementation doesn't work.

**Comment by cedriking** [comment]
Can you please provide any more details on what kind of issue are you having. Arkb does work with the bundlr network. We are the most used tool to deploy to Arweave (including to bundlr).
