### ISSUE TITLE
Arkb reports success, but url not found on arweave

### ISSUE THREAD

**Issue by thesoftwarejedi** [textury/arkb#58]
We use `arkb` from automation to upload claims files, but found this past week that the file uploaded is not available on arweave.

The url reported by arkb is `https://arweave.net/PX2jXfxTlWaIWkiwKKRtjgwfX7NaIoXSvddRPf61YzE`.

- Is there any way to trace why this didn't become active? 
- Is there a way to prevent this situation in `arkb`?

**Comment by kouraf** [comment]
Hi, can you send the file you are trying to upload, and how you are doing it !

**Comment by thesoftwarejedi** [comment]
The file uploads fine after doing it again.  It's part of weekly automation and has never been a problem before.

Upload command:

`arkb deploy ./output/myfile.json -w <keyfile> --tag-name App-Vendor --tag-value redacted --tag-name App-Name --tag-value redacted --tag-name App-Version --tag-value 0.1.0 --tag-name Content-Type --tag-value application/json`

**Comment by cedriking** [comment]
Hey @thesoftwarejedi the main gateway for Arweave have been having some issues and returning errors that aren't supposed to be returned. This is causing some data to be lost during the process of the upload and we end with corrupted deploys. As you mentioned, redeploying is the best solution during that case. 

Happy to see it worked doing a retry, and hopefully means the gateway is more stable.
