### ISSUE TITLE
Cached Bundlr Txs

### ISSUE THREAD

**Issue by xloem** [textury/arkb#60]
I noticed that the transaction cache only checks https://arweave.net/ to see if transactions are out there.

Transactions spend some time on https://bundler-node/tx/[txid]/data before reaching the  arweave gateway, it seems. I have one that's been a day or two.

**Comment by xloem** [comment]
This may not be an issue if there is something relevant I'm not understanding well.

**Comment by xloem** [comment]
Thanks for organising my issue. I'd love to know what I'm missing that it got closed without comment, although I haven't been using arkb recently.

When I made this, I was planning to review the caching code and modify the checks, but instead I've been using the subsidized 100KB upload deal so that duplicate transmissions don't cost me.

**Comment by fuadop** [comment]
Hi @xloem 👋🏾 ,

Arkb only caches transactions on the main gateway (https://arweave.net) currently. bundlr nodes are more than one and is always evovling. from https://bundlr.arweave.net to (https://node1.bundlr.network and https://node2.bundlr.network).

**Comment by xloem** [comment]
Thanks, I was actually a little confused on that, but are you kind of implying that arkb would need a pull request contributed in order to be concerned with caching txs sent to bundlr nodes?

**Comment by fuadop** [comment]
Bundlr is similar to a micro gateway, and they cache data before sending it to [arweave.net](http://arweave.net/), if I'm correct, that data is after deleted, so we cannot rely on bundlr.

**Comment by xloem** [comment]
Sorry, I mean to prevent retransmission. If the bundlr cache is not checked, then the same file can funded and confirmed twice. Does that sound right?
