### ISSUE TITLE
adding tags to arkb deploy

### ISSUE THREAD

**Issue by ron-appel** [textury/arkb#64]
after calling arkb with --tag-name name --tag-value value, when inspecting the completed transaction, this user-specified tag does not appear on the transaction tags list

**Comment by fuadop** [comment]
Hi @ron-appel 👋🏾 , this is a bug and would be fixed on the next npm update. I would keep you posted 😉 . Thanks for noticing and sorry about the hickup 🙇🏾

**Comment by ron-appel** [comment]
Thank you, seems to work!
