### ISSUE TITLE
manifest URL points to uploaded file

### ISSUE THREAD

**Issue by gherkins** [textury/arkb#67]
i uploaded 3 txt files for testing purposes.

what i would have expected:

> the manifest ID would point to the manifest json file, containing the infos for the uploaded files.

actual behaviour:

> the manifest ID points to file test2.txt (1st uploaded file)

the other 3 IDs point to the txt files as expected.

is that a bug, or am i missing something here?

actual output (minus the wallet part):

```
arkb deploy ./test --wallet keyfile.json --no-colors 
ID                                           Size           Fee              Type                          Path
CYkaOpn0AAf-pVeBsFJHIOJyEInXbdyWIIgDwRm79Nw  4.00 Bytes     0.000073237704   text/plain                    test2.txt
XQdNiyayy37kJWriRZktJC-XuBzy5hg2AzJzSz_02us  4.00 Bytes     0.000073237704   text/plain                    test1.txt
fk3_1TjnFiy94P-3BiqQ_G2NHI2ySka_Yf-ktw2BCh4  4.00 Bytes     0.000073237704   text/plain                    test3.txt
RqYfrkI89o6CHZTFTz42uVNZAFi9_3_PWHNJf5t2Bkc  280.00 Bytes   0.000073237704   application/x.arweave-manifest

Summary
All items will be deployed in a single bundle
Total size: 292.00 Bytes
Fees: 0.000292950816 + 0.000029295081 (10% arkb fee )
Total fee: 0.000322245897

[wallet info]

? Carefully check the above details are correct, then confirm to complete this upload Yes

Files deployed! Visit the following URL to see your deployed content:
https://arweave.net/RqYfrkI89o6CHZTFTz42uVNZAFi9_3_PWHNJf5t2Bkc
✨  Done in 33.78s.

**Comment by fuadop** [comment]
Hi @gherkins , this is the right behavior. The manifest json redirects to the index path in the path manifest Asper arweave specs.

**Comment by fuadop** [comment]
Also you can see a manifest.arkb file in your upload directory. It contains the path manifest.

**Comment by gherkins** [comment]
🙈 ok, i just managed to miss both of the options.    
Very cool, was worried for a second there...

Thank's a lot for the instant help!

**Comment by fuadop** [comment]
Funfact: you can access other files from the manifest tx url 

https://arweave.net/RqYfrkI89o6CHZTFTz42uVNZAFi9_3_PWHNJf5t2Bkc/test1.txt
https://arweave.net/RqYfrkI89o6CHZTFTz42uVNZAFi9_3_PWHNJf5t2Bkc/test2.txt
https://arweave.net/RqYfrkI89o6CHZTFTz42uVNZAFi9_3_PWHNJf5t2Bkc/test3.txt
