### ISSUE TITLE
need some help "Not Found"

### ISSUE THREAD

**Issue by soundreactor** [textury/arkb#77]
so i uploaded 1000 files but i cant access them with the web api. is that normal? i never had this problem before. 
for example:
"22.png":{"id":"Vl668XGb0bzyzaR-O1o13oKdGwFTbCJvQ5HtPNvvq-M"}
this is from the manifest file arkb generated.
can it happen that i payed for it but it didn't get mined? or that it's not hosted anymore?

**Comment by cedriking** [comment]
Hey @soundreactor looks like that transaction was dropped by the network.
You can always redeploy a directory using arkb and it will only redeploy the files that aren't on the permaweb. 

You will receive a new manifest tx ID with all the files, the missing ones will have a new txid and the ones that are already deployed will be using the same txid.

**Comment by soundreactor** [comment]
thank you. i will try that
