### ISSUE TITLE
Ability to specify custom content type during uploads

### ISSUE THREAD

**Issue by erik-rt** [textury/arkb#79]
Hey Textury team! Thank you for the great product.

I'm wondering if there's to add another option, something like `--content-type` to the CLI. I say this because I'm attempting to upload JSON files without the `.json` file extension and they are being uploaded as `application/octet-stream`. I would like to be able to upload with the `application/json` content type instead.

**Comment by kouraf** [comment]
Hello @erik-rt the content type is set automatically, can you share an example of a `json` that isn't set to  `application/json` when deployed ?

**Comment by kouraf** [comment]
Added in https://github.com/textury/arkb/pull/80

**Comment by erik-rt** [comment]
Hey @kouraf looks like you added the enhancement, that's much appreciated! Yes I was trying to upload typical JSON files, the only difference being that they did not have the `.json` extension (e.g., `0, 1, 2` instead of `0.json, 1.json, 2.json`).
