### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by ries9112** [textury/arkb#8]
Hello! First off, really great stuff with this tool, thank you for your work. 

I have a script which downloads the .json data for all parcels from Cryptovoxels (metaverse), and makes a backup of the .zip file using this tool. My script worked about 3-4 weeks without any issues, but about 12 days ago it started throwing the following error:
![image](https://user-images.githubusercontent.com/32306488/130304144-f404ba28-4a9a-49be-8762-a9eb5b21d7e3.png)

Any thoughts around this error? Nothing about that repo and automation through GitHub Actions has changed at all between when it was working and now. 

I am running `npm install -g @textury/arkb` and it doesn't error out for the runner, but it does give a warning that was not there while it was still working, which seems to be the source of the problem, but I'm not sure how to navigate/fix it:
![image](https://user-images.githubusercontent.com/32306488/130304327-a388e0b0-c541-481f-b92e-3f6bfe1a6e00.png)

I tried reproducing on my M1 Macbook Air but I can't get the install to work, and not really an expert in this particular area quite yet.

Would love any thoughts on the topic! Thank you for this tool!

**Comment by cedriking** [comment]
Hello @ries9112 .
We have contacted the redstone team to find out what is going on.
Thanks for pointing this issue out.

Best,
Cedrik.

**Comment by cedriking** [comment]
Hello @ries9112 , we have removed the `redstone-api` module which was causing this issue.

Can you please try now with the latest version? During this update we have removed the `@textury` scope. So to get the latest version you can simply do `arkb` without the scope.

Best,
Cedrik

**Comment by ries9112** [comment]
Thank you for the follow-up! 

I ran my workflow running `npm install -g arkb`, but ran into a similar issue of `MODULE_NOT_FOUND`:
![image](https://user-images.githubusercontent.com/32306488/130636511-b5ef338d-6dff-4aee-ac7b-25d4f0f67818.png)

**Comment by cedriking** [comment]
Hey @ries9112 👋🏼 
stream/promises is only available on version 15 and up of NodeJS.

**Comment by ries9112** [comment]
Thanks a lot, and sorry about that! 

I can confirm that worked, but yet another issue came up when I ran the code again:
![image](https://user-images.githubusercontent.com/32306488/130688291-5af76448-d179-489f-98b9-08fafc4d53cf.png)

Sorry if I missed something else, a lot I'm still learning 🙂

**Comment by ries9112** [comment]
I just tried running it locally on my mac and I ran into one of the issue shown previously on GitHub actions:
![image](https://user-images.githubusercontent.com/32306488/131203293-89f0997f-a99c-4dfe-951e-82d6f1bab61f.png)

I'm on v16.8.0 for node and v1.1.16 for arkb

**Comment by cedriking** [comment]
Ah this is in a repo using github actions! Can I please see that repo, I will be able to reproduce the issue quickly and see what's going on, thanks to just running that source.

**Comment by ries9112** [comment]
I made a new public repo here: https://github.com/ries9112/arkb_install_troubleshooting

This is the same as the one I'm using privately, with the exception of the arweave-keyfile. The issue however happens on the `arkb deploy CryptoVoxels-latest-archive.zip --auto-confirm --wallet arweave-keyfile-[key-here].json --tag.Tag-Name=CryptoVoxelsArchive` command, which you can't reproduce because I excluded the arweave-keyfile.

The workflow up to that last command works fine, see this run for example: https://github.com/ries9112/arkb_install_troubleshooting/runs/3450479051?check_suite_focus=true

Just ran my private repo with the `arkb deploy` command, and got the same error that I commented about 12h ago that I'm also getting on my M1 macbook:
![image](https://user-images.githubusercontent.com/32306488/131221084-5fc72e4d-f62a-4f96-b60d-a1d1b2e5054d.png)


Thanks for taking a look!

**Comment by cedriking** [comment]
I was able to find the issue, the error was related to a single file deploy and one of the latest changes I did. Sorry about that!

Version `1.1.17` has this bug fixed 🙌🏼

**Comment by ries9112** [comment]
Thank you! The automated script is back to working now without issues 🙂 thanks for looking into it!
