### ISSUE TITLE
Cache data uploaded elsewhere

### ISSUE THREAD

**Issue by xloem** [textury/arkb#81]
Hi,

I think it could be helpful if arkb had some way to add to its cache of what's already deployed without uploading content to do so, for example by providing a txid or url to scan, from a previous run on another machine.

This could give users a way to deduplicate their uploads across machines without having to understand the cache internals.

Just a thought!

**Comment by kouraf** [comment]
Hello @xloem, will discuss this idea and get back to you ! thnx for your thought :D

**Comment by xloem** [comment]
Thanks a bunch. I imagine this would be simpler if the peer or gateway API, or thegraph.com, provided for querying txs by data root. Not sure if there's some way visiting devs could help that happen some day. [edit: i guess that would leave out bundles completely, too]

**Comment by xloem** [comment]
Was the idea implemented? Apologies for the extra confusing text if this was closed to simplify concerns.
